import sqlLogo from "./assets/sql.svg";
import { FaCode } from "react-icons/fa";
import { Box, Flex, Image, chakra } from "@chakra-ui/react";
import { H2, H4 } from "./Typography";

export default function Skill() {
  return (
    <Box>
      <H2 textAlign={"center"} margin={10}>
        Skills
      </H2>
      <H4
        fontWeight={600}
        gap={1}
        my={0}
        display="flex"
        alignItems="center"
        textAlign="center"
        height="fit-content"
      >
        <FaCode />
        <chakra.span>Programming Language</chakra.span>
      </H4>

      <Flex marginTop={6} wrap={"wrap"} gap={4}>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Python</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>C++</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>C</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>R</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>JavaScript</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>TypeScript</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>JAVA</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/haskell/haskell-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Haskell</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>HTML5</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>CSS</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image src={sqlLogo} width={"24px"} height={"auto"} />
            <chakra.span>SQL</chakra.span>
          </H4>
        </Box>
      </Flex>
    </Box>
  );
}
