import sqlLogo from "./assets/sql.svg";
import tableau from "./assets/tableau-software.svg";
import reactqurylogo from "./assets/react-query.png";
import { FaCode } from "react-icons/fa";
import { AiFillCode } from "react-icons/ai";
import { BsFileEarmarkMedicalFill } from "react-icons/bs";
import { Box, Flex, Image, chakra } from "@chakra-ui/react";
import { H2, H4 } from "./Typography";

export default function Skill() {
  return (
    <Box>
      <H2 textAlign={"center"} margin={10}>
        Skills
      </H2>
      <H4
        fontWeight={600}
        gap={1}
        my={0}
        display="flex"
        alignItems="center"
        textAlign="center"
        height="fit-content"
      >
        <FaCode />
        <chakra.span>Programming Language</chakra.span>
      </H4>

      <Flex marginTop={6} marginBottom={6} wrap={"wrap"} gap={4}>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Python</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>C++</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>C</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/r/r-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>R</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>JavaScript</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>TypeScript</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>JAVA</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/haskell/haskell-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Haskell</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>HTML5</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>CSS</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image src={sqlLogo} width={"24px"} height={"auto"} />
            <chakra.span>SQL</chakra.span>
          </H4>
        </Box>
      </Flex>
      <H4
        fontWeight={600}
        gap={1}
        my={0}
        display="flex"
        alignItems="center"
        textAlign="center"
        height="fit-content"
      >
        <AiFillCode />
        <chakra.span>Framework & Libraries</chakra.span>
      </H4>
      <Flex marginTop={6} marginBottom={6} wrap={"wrap"} gap={4}>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>ReactJS</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>NodeJS</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/angularjs/angularjs-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>AngularJS</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image src={reactqurylogo} width={"24px"} height={"auto"} />
            <chakra.span>React Query</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>TailwindCSS</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Django Rest Framework</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/flask/flask-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Flask-Restful</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>MongoDB</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/d3js/d3js-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>D3.js</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>TensorFlow</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>OpenCV</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/numpy/numpy-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>NumPy</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Git</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <chakra.span>Keras</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <chakra.span>Scikit-learn</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <chakra.span>Mediapipe</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <chakra.span>cvzone</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <chakra.span>Scikit-image</chakra.span>
          </H4>
        </Box>
      </Flex>
      <H4
        fontWeight={600}
        gap={1}
        my={0}
        display="flex"
        alignItems="center"
        textAlign="center"
        height="fit-content"
      >
        <BsFileEarmarkMedicalFill />
        <chakra.span>Others</chakra.span>
      </H4>
      <Flex marginTop={6} marginBottom={6} wrap={"wrap"} gap={4}>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linux/linux-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Linux</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>GitHub</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image src={tableau} width={"24px"} height={"auto"} />
            <chakra.span>Tableau</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/figma/figma-original.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Figma</chakra.span>
          </H4>
        </Box>
        <Box
          bgColor={"gray.100"}
          borderRadius={"5px"}
          width={"fit-content"}
          padding={1.5}
        >
          <H4
            display="flex"
            alignItems="center"
            textAlign="center"
            height="fit-content"
            fontSize={"14px"}
            lineHeight={"24px"}
            fontWeight={600}
            gap={1}
            my={0}
          >
            <Image
              src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-line.svg"
              width={"24px"}
              height={"auto"}
            />
            <chakra.span>Jenkins</chakra.span>
          </H4>
        </Box>
      </Flex>
    </Box>
  );
}
